import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./css/globals.css";

import { Flowbite, ThemeModeScript } from "flowbite-react";
import customTheme from "@/utils/theme/custom-theme";

import { CustomizerContextProvider } from "@/app/context/CustomizerContext";
import { UserDataProvider } from "@/app/context/UserDataContext";

import ApolloProviders from "./ApolloProviders"; // <-- Apollo Client Provider
import NextTopLoader from "nextjs-toploader";

const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Modernize - Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <ThemeModeScript />
      </head>

      {/* Body */}
      <body className={`${plus_jakarta_sans.className}`}>
        {/* Apollo provider MUST be top-level wrapper for GraphQL authentication */}
        <ApolloProviders>
          {/* UI Theme providers */}
          <Flowbite theme={{ theme: customTheme }}>
            <CustomizerContextProvider>
              <UserDataProvider>
                {/* Page loading bar */}
                <NextTopLoader color="var(--color-primary)" />

                {/* The rendered page */}
                {children}
              </UserDataProvider>
            </CustomizerContextProvider>
          </Flowbite>
        </ApolloProviders>
      </body>
    </html>
  );
}
